# General training loop config
# Based on https://arxiv.org/pdf/2011.14826.pdf
run_name: &run_name 'breakout-rainbow'
train_steps: 10000000
test_frequency: 100
test_num_episodes: 10
saving_schedule:
  name: 'PeriodicSchedule'
  kwargs:
    off_value: False
    on_value: True
    period: 15000
save_dir: 'experiment'

# Environment config
environment:
  name: 'MinAtarEnv'
  kwargs:
    env_name: 'breakout'

# List of agents for the experiment. In single agent, only the first agent in
# the list is used.
agent:
  name: 'RainbowDQNAgent'
  kwargs:
    qnet:
      name: 'ConvNetwork'
      kwargs:
        channels: [16]
        mlp_layers: [128]
        kernel_sizes: [3]
        strides: [1]
        paddings: [0]
        normalization_factor: 1
        noisy: True
        std_init: 0.5
    hidden_dim: 128
    optimizer_fn:
      name: 'Adam'
      kwargs:
        lr: 0.00025
        eps: 0.0003125
    id: 0
    n_step: &n_step 3
    replay_buffer:
      name: 'PrioritizedReplayBuffer'
      kwargs:
        seed: 43
        capacity: 100000
        stack_size: 1
        n_step: *n_step
        gamma: .99
    discount_rate: .99
    target_net_update_schedule:
      name: 'PeriodicSchedule'
      kwargs:
        off_value: False
        on_value: True
        period: 1000
    epsilon_schedule:
      name: 'LinearSchedule'
      kwargs:
        init_value: 1
        end_value: 0.1
        steps: 100000
    learn_schedule:
      name: 'SwitchSchedule'
      kwargs:
        off_value: False
        on_value: True
        steps: 5000
    update_period_schedule:
      name: 'PeriodicSchedule'
      kwargs:
        off_value: False
        on_value: True
        period: 4
    seed: 43
    batch_size: 32
    device: 'cuda'
    log_frequency: 1000
    double: True
    distributional: True
    dueling: True
    noisy: True
    std_init: .5
    use_eps_greedy: False
    v_min: -100.0
    v_max: 100.0
    atoms: 51

# List of logger configs used.
loggers:
  -
    name: ChompLogger
    kwargs: {}
  -
    name: WandbLogger
    kwargs:
      project_name: Hive-v2
      run_name: *run_name
      mode: "online"
      settings_str: 'fork'
