name: 'SingleAgentRunner'
kwargs:
  experiment_manager:
    name: 'Experiment'
    kwargs:
      name: &run_name 'gym-dqn'
      save_dir: 'experiment'
      saving_schedule:
        name: 'PeriodicSchedule'
        kwargs:
          off_value: False
          on_value: True
          period: 10000
  train_steps: 50000
  test_frequency: 250
  test_episodes: 10
  max_steps_per_episode: 1000
  environment:
    name: 'GymEnv'
    kwargs:
      env_name: 'CartPole-v0'

  agent:
    name: 'DRQNAgent'
    kwargs:
      representation_net:
        name: 'ConvRNNNetwork'
        kwargs:
          channels: [32, 64, 64]
          kernel_sizes: [8, 4, 3]
          strides: [4, 2, 1]
          paddings: [2, 2, 1]
          mlp_layers: [512]
          sequence_fn:
            name: 'LSTM'
            kwargs:
              rnn_hidden_size: 128
              num_rnn_layers: 1
      optimizer_fn:
        name: 'RMSpropTF'
        kwargs:
          lr: 0.00025
          alpha: .95
          eps: 0.00001
          centered: True
      init_fn:
        name: 'xavier_uniform'
      loss_fn:
        name: 'SmoothL1Loss'
      replay_buffer:
        name: 'RecurrentReplayBuffer'
        kwargs:
          capacity: 1000000
          gamma: &gamma .99
          rnn_type: 'lstm'
          rnn_hidden_size: 128
      max_seq_len: 10
      discount_rate: *gamma
      reward_clip: 1
      update_period_schedule:
        name: 'PeriodicSchedule'
        kwargs:
          off_value: False
          on_value: True
          period: 4
      target_net_update_schedule:
        name: 'PeriodicSchedule'
        kwargs:
          off_value: False
          on_value: True
          period: 8000
      epsilon_schedule:
        name: 'LinearSchedule'
        kwargs:
          init_value: 1.0
          end_value: .01
          steps: 250000
      test_epsilon: .001
      min_replay_history: 200
      device: 'cuda'
      log_frequency: 1000
  # List of logger configs used.
  loggers:
    -
      name: ChompLogger
    -
      name: WandbLogger
      kwargs:
        project: Hive
        name: *run_name
        resume: "allow"
        start_method: "fork"
