name: 'SingleAgentRunner'
kwargs:
  experiment_manager:
    name: 'Experiment'
    kwargs:
      name: &run_name 'gym-ppo'
      save_dir: 'experiment'
      saving_schedule:
        name: 'PeriodicSchedule'
        kwargs:
          off_value: False
          on_value: True
          period: 10000

  train_steps: 500000
  test_frequency: 1000
  test_episodes: 10
  max_steps_per_episode: 500
  stack_size: &stack_size 1
  environment:
    name: 'GymEnv'
    kwargs:
      env_name: 'CartPole-v1'
    
  agent:
    name: 'PPOAgent'
    kwargs:
      actor_net:
        name: 'MLPNetwork'
        kwargs: 
          hidden_units: [256, 256]
      critic_net:
        name: 'MLPNetwork'
        kwargs: 
          hidden_units: [256, 256]
      replay_buffer:
        name: 'OnPolicyReplayBuffer'
        kwargs:
          use_gae: True
          gae_lambda: .95
      optimizer_fn:
        name: 'Adam'
        kwargs:
          lr: .00025
      discount_rate: .99
      grad_clip: .5
      clip_coefficient: .2
      entropy_coefficient: .01
      clip_value_loss: True
      value_fn_coefficient: .5
      transitions_per_update: 2048
      num_epochs_per_update: 4
      normalize_advantages: True
      batch_size: 128
      device: 'cuda'
      id: 'agent'
      init_fn: 
        name: 'orthogonal'
  # List of logger configs used.
  loggers:
    -
      name: ChompLogger
    -
      name: WandbLogger
      kwargs:
        project: Hive
        name: *run_name
        resume: "allow"
        start_method: "fork"
