run_name: &run_name 'gym-ppo'
train_steps: 500000
test_frequency: 1000
test_episodes: 10
max_steps_per_episode: 500
stack_size: &stack_size 1
save_dir: 'experiment'
saving_schedule:
  name: 'PeriodicSchedule'
  kwargs:
    off_value: False
    on_value: True
    period: 10000

environment:
  name: 'GymEnv'
  kwargs:
    env_name: 'CartPole-v1'
    
agent:
  name: 'PPOAgent'
  kwargs:
    actor_net:
      name: 'MLPNetwork'
      kwargs: 
        hidden_units: [64, 64]
        activation_fn:
          name: 'Tanh'
    critic_net:
      name: 'MLPNetwork'
      kwargs: 
        hidden_units: [64, 64]
        activation_fn:
          name: 'Tanh'
    replay_buffer:
      name: 'PPOReplayBuffer'
      kwargs:
        use_gae: True
        gae_lambda: .95
    optimizer_fn:
      name: 'Adam'
      kwargs:
        lr: .00025
    discount_rate: .99
    grad_clip: .5
    clip_coef: .2
    ent_coef: .01
    clip_vloss: True
    vf_coef: .5
    transitions_per_update: 1024
    num_epochs_per_update: 4
    normalize_advantages: True
    batch_size: 256
    device: 'cuda'
    id: 'agent'
    init_fn: 
      name: 'orthogonal'
# List of logger configs used.
loggers:
  -
    name: ChompLogger
  -
    name: WandbLogger
    kwargs:
      project: Hive
      name: *run_name
      resume: "allow"
      start_method: "fork"
