name: 'SingleAgentRunner'
kwargs:
  experiment_manager:
    name: 'Experiment'
    kwargs:
      name: &run_name 'gym-rainbow'
      save_dir: 'experiment'
      saving_schedule:
        name: 'PeriodicSchedule'
        kwargs:
          off_value: False
          on_value: True
          period: 10000
  train_steps: 50000
  test_frequency: 200
  test_episodes: 10
  max_steps_per_episode: 1000
  stack_size: &stack_size 1
  environment:
    name: 'GymEnv'
    kwargs:
      env_name: 'CartPole-v0'

  agent:
    name: 'RainbowDQNAgent'
    kwargs:
      representation_net:
        name: 'MLPNetwork'
        kwargs:
          hidden_units: [256, 256]
      stack_size: 1
      optimizer_fn:
        name: 'Adam'
        kwargs: {}
      loss_fn:
        name: "SmoothL1Loss"
      replay_buffer:
        name: 'CircularReplayBuffer'
        kwargs:
          capacity: 10000
      discount_rate: .99
      reward_clip: 1
      target_net_update_schedule:
        name: 'PeriodicSchedule'
        kwargs:
          off_value: False
          on_value: True
          period: 100
      update_period_schedule:
        name: 'PeriodicSchedule'
        kwargs:
          off_value: False
          on_value: True
          period: 1
      epsilon_schedule:
        name: 'ConstantSchedule'
        kwargs:
          value: .01
      test_epsilon: .001
      min_replay_history: 500
      device: 'cuda'
      log_frequency: 100
      batch_size: 32
      double: False
      distributional: False
      dueling: False
      noisy: True
      std_init: .5
      use_eps_greedy: False
      v_min: 0
      v_max: 200.0
      atoms: 51

  # List of logger configs used.
  loggers:
    -
      name: ChompLogger
    -
      name: WandbLogger
      kwargs:
        project: Hive
        name: *run_name
        resume: "allow"
        start_method: "fork"
