# General training loop config
run_name: &run_name 'gym-random'
train_steps: 50000
test_frequency: 200
test_episodes: 10
max_steps_per_episode: 1000
saving_schedule:
  name: 'PeriodicSchedule'
  kwargs:
    off_value: False
    on_value: True
    period: 10000
save_dir: 'experiment'

# Environment config
environment:
  name: 'GymEnv'
  kwargs:
    env_name: 'CartPole-v0'

# List of agents for the experiment. In single agent, only the first agent in
# the list is used.
agent: 
  name: 'RandomAgent'
  kwargs:
    id: 0

# List of logger configs used.
loggers:
  -
    name: ChompLogger
    kwargs: {}
  -
    name: WandbLogger
    kwargs:
      project: Hive
      name: *run_name
      resume: "allow"
      start_method: "fork"
