wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1663535059
    t:
      1:
      - 1
      - 55
      3:
      - 13
      4: 3.7.13
      5: 0.12.16
      8:
      - 3
      - 8
agent:
  desc: null
  value:
    kwargs:
      device: cuda
      discount_rate: 0.99
      epsilon_schedule:
        kwargs:
          end_value: 0.01
          init_value: 1.0
          steps: 25
        name: LinearSchedule
      init_fn:
        kwargs: {}
        name: xavier_uniform
      log_frequency: 1000
      loss_fn:
        kwargs: {}
        name: SmoothL1Loss
      min_replay_history: 4
      optimizer_fn:
        kwargs:
          alpha: 0.95
          centered: true
          eps: 1.0e-05
          lr: 0.00025
        name: RMSpropTF
      replay_buffer:
        kwargs:
          capacity: 1000000
          gamma: 0.99
          stack_size: 4
        name: CircularReplayBuffer
      representation_net:
        kwargs:
          channels:
          - 32
          - 64
          - 64
          kernel_sizes:
          - 8
          - 4
          - 3
          mlp_layers:
          - 512
          paddings:
          - 2
          - 2
          - 1
          strides:
          - 4
          - 2
          - 1
        name: ConvNetwork
      reward_clip: 1
      target_net_update_schedule:
        kwargs:
          off_value: false
          on_value: true
          period: 80
        name: PeriodicSchedule
      test_epsilon: 0.001
      update_period_schedule:
        kwargs:
          off_value: false
          on_value: true
          period: 4
        name: PeriodicSchedule
    name: DQNAgent
debugger:
  desc: null
  value:
    kwargs:
      check_type:
      - name: Observation
      - name: Weights
    name: Debugger
environment:
  desc: null
  value:
    kwargs:
      env_name: Asterix
    name: AtariEnv
loggers:
  desc: null
  value:
    kwargs:
      logger_list:
      - kwargs: {}
        name: ChompLogger
      - kwargs:
          name: atari-dqn
          project: Hive
          resume: allow
          start_method: thread
        name: WandbLogger
    name: CompositeLogger
max_steps_per_episode:
  desc: null
  value: 27
run_name:
  desc: null
  value: atari-dqn
save_dir:
  desc: null
  value: experiment
saving_schedule:
  desc: null
  value:
    kwargs:
      off_value: false
      on_value: true
      period: 10
    name: PeriodicSchedule
stack_size:
  desc: null
  value: 4
test_episodes:
  desc: null
  value: 10
test_frequency:
  desc: null
  value: 5000
train_steps:
  desc: null
  value: 5000
