name: 'SingleAgentRunner'
kwargs:
  experiment_manager:
    name: 'Experiment'
    kwargs:
      name: &run_name 'atari-drqn'
      save_dir: 'experiment'
      saving_schedule:
        name: 'PeriodicSchedule'
        kwargs:
          off_value: False
          on_value: True
          period: 1000000
  train_steps: 50000000
  test_frequency: 250000
  test_episodes: 10
  max_steps_per_episode: 27000
  environment:
    name: 'GymEnv'
    kwargs:
      env_name: 'ALE/Asterix-v5'
      repeat_action_probability: 0.25 # probality = 1 / sticky_action_number
      frameskip: 1 # this is required to be set to expose frameskip in wrapper 
      env_wrappers:
        - name: AtariPreprocessing
          kwargs:
            frame_skip: 4
            grayscale_newaxis: True
            screen_size: 84
        # This wrapper converts image from the TF format (channels last)
        # to the PyTorch format (channels first)
        - name: PermuteImageWrapper 

  agent:
    name: 'DRQNAgent'
    kwargs:
      representation_net:
        name: 'ConvNetwork'
        kwargs:
          channels: [32, 64, 64]
          kernel_sizes: [8, 4, 3]
          strides: [4, 2, 1]
          paddings: [2, 2, 1]
          mlp_layers: [512]
      sequence_fn:
        name: 'LSTM'
        kwargs:
          rnn_hidden_size: 128
          num_rnn_layers: 2
      optimizer_fn:
        name: 'RMSpropTF'
        kwargs:
          lr: 0.00025
          alpha: .95
          eps: 0.00001
          centered: True
      init_fn:
        name: 'xavier_uniform'
      loss_fn:
        name: 'SmoothL1Loss'
      replay_buffer:
        name: 'RecurrentReplayBuffer'
        kwargs:
          capacity: 1000000
          gamma: &gamma .99
      max_seq_len: 10
      discount_rate: *gamma
      reward_clip: 1
      update_period_schedule:
        name: 'PeriodicSchedule'
        kwargs:
          off_value: False
          on_value: True
          period: 4
      target_net_update_schedule:
        name: 'PeriodicSchedule'
        kwargs:
          off_value: False
          on_value: True
          period: 8000
      epsilon_schedule:
        name: 'LinearSchedule'
        kwargs:
          init_value: 1.0
          end_value: .01
          steps: 250000
      test_epsilon: .001
      min_replay_history: 200
      device: 'cuda'
      log_frequency: 1000
  # List of logger configs used.
  loggers:
    -
      name: ChompLogger
    -
      name: WandbLogger
      kwargs:
        project: Hive
        name: *run_name
        resume: "allow"
        start_method: "fork"