run_name: &run_name 'atari-rainbow'
train_steps: 50000000
test_frequency: 250000
test_episodes: 10
max_steps_per_episode: 27000
stack_size: &stack_size 4
save_dir: 'experiment'
saving_schedule:
  name: 'PeriodicSchedule'
  kwargs:
    off_value: False
    on_value: True
    period: 1000000
environment:
  name: 'AtariEnv'
  kwargs:
    env_name: 'Asterix'

agent:
  name: 'RainbowDQNAgent'
  kwargs:
    representation_net:
      name: 'ConvNetwork'
      kwargs:
        channels: [32, 64, 64]
        kernel_sizes: [8, 4, 3]
        strides: [4, 2, 1]
        paddings: [2, 2, 1]
        mlp_layers: [512]
    optimizer_fn:
      name: 'Adam'
      kwargs:
        lr: 0.0000625
        eps: 0.00015
    init_fn:
      name: 'variance_scaling'
      kwargs:
        scale: 0.577350269
    loss_fn:
      name: "MSELoss"
    n_step: &n_step 3
    replay_buffer:
      name: 'PrioritizedReplayBuffer'
      kwargs:
        capacity: 1000000
        stack_size: *stack_size
        gamma: &gamma .99
        n_step: *n_step
    discount_rate: *gamma
    reward_clip: 1
    update_period_schedule:
      name: 'PeriodicSchedule'
      kwargs:
        off_value: False
        on_value: True
        period: 4
    target_net_update_schedule:
      name: 'PeriodicSchedule'
      kwargs:
        off_value: False
        on_value: True
        period: 8000
    epsilon_schedule:
      name: 'LinearSchedule'
      kwargs:
        init_value: 1.0
        end_value: .01
        steps: 250000
    test_epsilon: .001
    min_replay_history: 20000
    device: 'cuda'
    log_frequency: 1000
    batch_size: 32
    double: False
    distributional: True
    dueling: False
    noisy: False
    use_eps_greedy: True
    v_min: -10.0
    v_max: 10.0
    atoms: 51

# List of logger configs used.
loggers:
  -
    name: ChompLogger
  -
    name: WandbLogger
    kwargs:
      project: Hive
      name: *run_name
      resume: "allow"
      start_method: "fork"
