# General training loop config
run_name: &run_name 'hanabi-r2d2'
train_steps: 100000000
test_frequency: 100000
test_num_episodes: 10
self_play: True
num_agents: &num_agents 2
max_seq_len: &max_seq_len 10
stack_size: &stack_size 1
saving_schedule:
  name: 'PeriodicSchedule'
  kwargs:
    off_value: False
    on_value: True
    period: 500000
save_dir: 'experiment'

# Environment config
environment:
  name: 'PettingZooEnv'
  kwargs:
    env_name: 'hanabi_v4'
    env_family: 'classic'
    num_players: *num_agents

# List of agents for the experiment. In single agent, only the first agent in
# the list is used.
agent:
  -
    name: 'LegalMovesR2D2Agent'
    kwargs:
      representation_net:
        name: 'MLPRNNNetwork'
        kwargs:
          mlp_layers: [512,512]
          sequence_fn:
            name: 'LSTM'
            kwargs:
              rnn_hidden_size: 128
              num_rnn_layers: 1
      optimizer_fn:
        name: 'Adam'
        kwargs:
          lr: 0.000025
          eps: 0.00003125
      init_fn:
        name: 'variance_scaling'
      id: 0
      replay_buffer:
        name: 'LegalMovesRecurrentBuffer'
        kwargs:
          capacity: 1000000
          max_seq_len: *max_seq_len
          action_dim: 20
          num_players_sharing_buffer: *num_agents
          gamma: 0.99
      max_seq_len: *max_seq_len
      discount_rate: .99
      update_period_schedule:
        name: 'PeriodicSchedule'
        kwargs:
          off_value: False
          on_value: True
          period: 4
      target_net_update_schedule:
        name: 'PeriodicSchedule'
        kwargs:
          off_value: False
          on_value: True
          period: 500
      epsilon_schedule:
        name: 'LinearSchedule'
        kwargs:
          init_value: 1
          end_value: 0.0
          steps: 1000
      test_epsilon: 0
      min_replay_history: 500
      batch_size: 32
      device: 'cuda'
      log_frequency: 100
      double: False

# List of logger configs used.
loggers:
  -
    name: ChompLogger
    kwargs: {}
  -
    name: WandbLogger
    kwargs:
      project: Hive
      name: *run_name
      mode: "online"
      start_method: 'fork'