# General training loop config
run_name: &run_name 'MABC-dqn'
train_steps: 50000
test_frequency: 25
test_num_episodes: 10
saving_schedule:
  name: 'PeriodicSchedule'
  kwargs:
    off_value: False
    on_value: True
    period: 15000
save_dir: 'experiment'

# Environment config
environment:
  name: 'MultiAgentDiscEnv'
  kwargs:
    env_name: 'MABC-v0'
    num_players: 2

# List of agents for the experiment. In single agent, only the first agent in
# the list is used.
agents: 
  - 
    name: 'DQNAgent'
    kwargs:
      qnet:
        name: 'DiscObsSimpleMLP'
        kwargs: 
          hidden_units: 256
          num_hidden_layers: 2
      optimizer_fn:
        name: 'Adam'
        kwargs: {}
      id: 0
      replay_buffer:
        name: 'CircularReplayBuffer'
        kwargs:
          seed: 42
          size: 10000
      discount_rate: .9
      target_net_update_schedule:
        name: 'PeriodicSchedule'
        kwargs:
          off_value: False
          on_value: True
          period: 100
      epsilon_schedule:
        name: 'ConstantSchedule'
        kwargs:
          value: .01
      learn_schedule:
        name: 'SwitchSchedule'
        kwargs:
          off_value: False
          on_value: True
          steps: 500
      seed: 42
      batch_size: 128
      device: 'cpu'
      log_frequency: 100
  - 
    name: 'DQNAgent'
    kwargs:
      qnet:
        name: 'DiscObsSimpleMLP'
        kwargs: 
          hidden_units: 256
          num_hidden_layers: 2
      optimizer_fn:
        name: 'Adam'
        kwargs: {}
      id: 1
      replay_buffer:
        name: 'CircularReplayBuffer'
        kwargs:
          seed: 43
          size: 10000
      discount_rate: .9
      target_net_update_schedule:
        name: 'PeriodicSchedule'
        kwargs:
          off_value: False
          on_value: True
          period: 100
      epsilon_schedule:
        name: 'ConstantSchedule'
        kwargs:
          value: .01
      learn_schedule:
        name: 'SwitchSchedule'
        kwargs:
          off_value: False
          on_value: True
          steps: 500
      seed: 43
      batch_size: 128
      device: 'cpu'
      log_frequency: 100

# List of logger configs used.
loggers:
  -
    name: ChompLogger
    kwargs: {}
  -
    name: WandbLogger
    kwargs:
      project_name: Hive-v1
      run_name: *run_name
      offline: False
