# General training loop config
run_name: &run_name 'MABC'
train_steps: 30000
test_frequency: 2
test_num_episodes: 2
self_play: False
staged_learning: False
num_agents: 2
stack_size: &stack_size 3
saving_schedule:
  name: 'PeriodicSchedule'
  kwargs:
    off_value: False
    on_value: True
    period: 15000
save_dir: &save_dir 'experiment'

# Environment config
environment:
  name: 'MultiAgentDiscEnv'
  kwargs:
    env_name: 'MABC-v0'
    num_players: 2
    seed: 42

# List of agents for the experiment. In single agent, only the first agent in
# the list is used.
agents:
  -
    name: 'DQNAgent_disc_obs'
    kwargs:
      qnet:
        name: 'DiscObsSimpleMLP'
        kwargs:
          hidden_units: 256
          num_hidden_layers: 2
      optimizer_fn:
        name: 'Adam'
        kwargs: {}
      id: 0
      replay_buffer:
        name: 'EfficientCircularBuffer'
        kwargs:
          seed: 42
          capacity: 10000
          stack_size: *stack_size
      discount_rate: .9
      target_net_update_schedule:
        name: 'PeriodicSchedule'
        kwargs:
          off_value: False
          on_value: True
          period: 100
      learn_schedule:
        name: 'SwitchSchedule'
        kwargs:
          off_value: False
          on_value: True
          steps: 500
      seed: 42
      batch_size: 128
      device: 'cpu'
      log_frequency: 10000
  -
    name: 'DQNAgent_disc_obs'
    kwargs:
      qnet:
        name: 'DiscObsSimpleMLP'
        kwargs:
          hidden_units: 256
          num_hidden_layers: 2
      optimizer_fn:
        name: 'Adam'
        kwargs: {}
      id: 1
      replay_buffer:
        name: 'EfficientCircularBuffer'
        kwargs:
          seed: 43
          capacity: 10000
          stack_size: *stack_size
      discount_rate: .9
      target_net_update_schedule:
        name: 'PeriodicSchedule'
        kwargs:
          off_value: False
          on_value: True
          period: 100
      learn_schedule:
        name: 'SwitchSchedule'
        kwargs:
          off_value: False
          on_value: True
          steps: 500
      seed: 43
      batch_size: 128
      device: 'cpu'
      log_frequency: 10000

# List of logger configs used.
loggers:
  -
    name: WandbLogger
    kwargs:
      project_name: Hive-v1
      run_name: *run_name
      save_dir: *save_dir
      #mode: "offline"