# General training loop config
run_name: &run_name 'breakout-dqn-s0'
train_steps: 200000000
test_frequency: 2000000
test_num_episodes: 10
resume: True
stack_size: &stack_size 4
saving_schedule:
  name: 'PeriodicSchedule'
  kwargs:
    off_value: False
    on_value: True
    period: 2000000
save_dir: './experiment'

# Environment config
environment:
  name: 'AtariEnv'
  kwargs:
    env_name: 'Breakout'

# List of agents for the experiment. In single agent, only the first agent in
# the list is used.
agent:
  name: 'DQNAgent'
  kwargs:
    qnet:
      name: 'NatureAtariDQNModel'
    optimizer_fn:
      name: 'RMSprop'
      kwargs:
        lr: 0.00025
        weight_decay: 0
        centered: True
        momentum: 0.95
        eps: 0.01
        alpha: 0.95
    id: 0
    replay_buffer:
      name: 'EfficientCircularBuffer'
      kwargs:
        seed: 0
        capacity: 1000000
        stack_size: *stack_size
    discount_rate: .99
    reward_clip: 1.
    target_net_update_schedule:
      name: 'PeriodicSchedule'
      kwargs:
        off_value: False
        on_value: True
        period: 40000
    update_period_schedule:
      name: 'PeriodicSchedule'
      kwargs:
        off_value: False
        on_value: True
        period: 4
    epsilon_schedule:
      name: 'LinearSchedule'
      kwargs:
        init_value: 1
        end_value: 0.05
        steps: 4000000
    learn_schedule:
      name: 'SwitchSchedule'
      kwargs:
        off_value: False
        on_value: True
        steps: 200000
    seed: 0
    batch_size: 32
    device: 'cuda'
    log_frequency: 1000

# List of logger configs used.
loggers:
  -
    name: ChompLogger
    kwargs: {}
  -
    name: WandbLogger
    kwargs:
      project_name: Hive-v1
      run_name: *run_name
      mode: "offline"
      id: "re-hive-dqn-atari-breakout-s0-0"
      resume: "allow"
      settings: "fork"