run_name: &run_name 'mujoco-ppo'
train_steps: 2000000
test_frequency: 20000
test_episodes: 5
max_steps_per_episode: 100000
stack_size: &stack_size 1
save_dir: 'experiment'
saving_schedule:
  name: 'PeriodicSchedule'
  kwargs:
    off_value: False
    on_value: True
    period: 500000
environment:
  name: 'GymEnv'
  kwargs:
    env_name: 'Hopper-v3'
    wrappers:
      - 
        name: ClipAction

agent:
  name: 'PPOAgent'
  kwargs:
    actor_net:
      name: 'MLPNetwork'
      kwargs: 
        hidden_units: [64, 64]
    critic_net:
      name: 'MLPNetwork'
      kwargs: 
        hidden_units: [64, 64]
    observation_normalization:
      name: 'NormalizationFn'
    reward_normalization:
      name: 'NormalizationFn'
    replay_buffer:
      name: 'PPOReplayBuffer'
      kwargs:
        use_gae: True
        gae_lambda: .95
    optimizer_fn:
      name: 'Adam'
      kwargs:
        lr: .0003
    discount_rate: .99
    grad_clip: .5
    clip_coef: .2
    ent_coef: .0
    clip_vloss: True
    vf_coef: .5
    transitions_per_update: 2048
    num_epochs_per_update: 10
    normalize_advantages: True
    batch_size: 64
    device: 'cuda'
    id: 'agent'
    init_fn: 
      name: 'orthogonal'
    reward_clip: 10

# List of logger configs used.
loggers:
  -
    name: ChompLogger
  -
    name: WandbLogger
    kwargs:
      project: Hive
      name: *run_name
      resume: "allow"
      start_method: "fork"
