# General training loop config
run_name: &run_name 'switch-dqn'
train_steps: 500000
test_frequency: 100
test_num_episodes: 5
self_play: False
num_agents: 2
stack_size: &stack_size 4
saving_schedule:
  name: 'PeriodicSchedule'
  kwargs:
    off_value: False
    on_value: True
    period: 15000
save_dir: 'experiment'

# Environment config
environment:
  name: 'MarlGridEnv'
  kwargs:
    env_name: 'MarlGrid-2AgentSwitch8x8-v0'
    num_players: 2

# List of agents for the experiment. In single agent, only the first agent in
# the list is used.
agents:
  -
    name: 'DQNAgent'
    kwargs:
      qnet:
        name: 'SimpleConvModel'
        kwargs:
          channels: [ 16, 32, 32 ]
          kernel_sizes: [ 8, 4, 3 ]
          strides: [ 4, 2, 1 ]
          paddings: [ 0, 1, 1 ]
          mlp_layers: [ 128 ]
      optimizer_fn:
        name: 'Adam'
        kwargs: {}
      id: 0
      replay_buffer:
        name: 'EfficientCircularBuffer'
        kwargs:
          seed: 42
          capacity: 100000
          stack_size: *stack_size
      discount_rate: .9
      target_net_update_schedule:
        name: 'PeriodicSchedule'
        kwargs:
          off_value: False
          on_value: True
          period: 1000
      epsilon_schedule:
        name: 'ConstantSchedule'
        kwargs:
          value: .1
      learn_schedule:
        name: 'SwitchSchedule'
        kwargs:
          off_value: False
          on_value: True
          steps: 5000
      seed: 42
      batch_size: 256
      device: 'cuda'
      log_frequency: 100
  -
    name: 'DQNAgent'
    kwargs:
      qnet:
        name: 'SimpleConvModel'
        kwargs:
          channels: [ 16, 32, 32 ]
          kernel_sizes: [ 8, 4, 3 ]
          strides: [ 4, 2, 1 ]
          paddings: [ 0, 1, 1 ]
          mlp_layers: [ 128 ]
      optimizer_fn:
        name: 'Adam'
        kwargs: {}
      id: 1
      replay_buffer:
        name: 'EfficientCircularBuffer'
        kwargs:
          seed: 42
          capacity: 100000
          stack_size: *stack_size
      discount_rate: .9
      target_net_update_schedule:
        name: 'PeriodicSchedule'
        kwargs:
          off_value: False
          on_value: True
          period: 1000
      epsilon_schedule:
        name: 'ConstantSchedule'
        kwargs:
          value: .1
      learn_schedule:
        name: 'SwitchSchedule'
        kwargs:
          off_value: False
          on_value: True
          steps: 5000
      seed: 43
      batch_size: 256
      device: 'cuda'
      log_frequency: 100

# List of logger configs used.
loggers:
  -
    name: ChompLogger
    kwargs: {}
  -
    name: WandbLogger
    kwargs:
      project_name: Hive-v1
      run_name: *run_name
      mode: "online"
