# General training loop config
run_name: &run_name 'minigrid-empty-5x5-image-dqn'
train_steps: 50000
test_frequency: 10
test_num_episodes: 1
seed: 42
saving_schedule:
  name: 'ConstantSchedule'
  kwargs:
    value: False
save_dir: 'experiment'

# Environment config
environment:
  name: 'MiniGridEnv'
  kwargs:
    env_name: 'MiniGrid-Empty-5x5-v0'

# List of agents for the experiment. In single agent, only the first agent in
# the list is used.
agent:
  name: 'DQNAgent'
  kwargs:
    qnet:
      name: 'SimpleConvModel'
      kwargs:
        channels: [16, 32, 64]
        kernel_sizes: [3, 3, 3]
        mlp_layers: [128]
    optimizer_fn:
      name: 'Adam'
      kwargs:
        lr: 0.001
    id: 0
    replay_buffer:
      name: 'EfficientCircularBuffer'
      kwargs:
        seed: 42
        capacity: 20000
    discount_rate: .9
    target_net_update_schedule:
      name: 'PeriodicSchedule'
      kwargs:
        off_value: False
        on_value: True
        period: 5000
    epsilon_schedule:
      name: 'LinearSchedule'
      kwargs:
        init_value: 1
        end_value: 0.05
        steps: 25000
    learn_schedule:
      name: 'SwitchSchedule'
      kwargs:
        off_value: False
        on_value: True
        steps: 1000
    seed: 42
    batch_size: 256
    device: 'cuda'
    log_frequency: 100

# List of logger configs used.
loggers:
  -
    name: ChompLogger
    kwargs: {}
  -
    name: WandbLogger
    kwargs:
      project_name: Hive-v1
      run_name: *run_name
      mode: "online"

